### ISSUE TITLE
rpg-js ubuntu `npm i` error

### ISSUE THREAD

**Issue by LehaoLin** [RSamaium/RPG-JS#156]
OS: Ubuntu 18.04
Node version: v14.17.6
Error happens when `npm i`

```sh
> deasync@0.1.21 install /root/my-rpg-game/node_modules/deasync
> node ./build.js

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '/root/my-rpg-game/node_modules/deasync/build.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by RSamaium** [comment]
Hello,

Thanks for the feedback but I can't reproduce the problem, it works on my side.

Maybe try to update the `deasync` module:

`npm install deasync@latest`
