### ISSUE TITLE
GameEngine.ts:125 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'complete')

### ISSUE THREAD

**Issue by dominx99** [RSamaium/RPG-JS#211]
It is related to #209 because also occurs when I try to change map (black screen & loading)

Steps to reproduce:

1. Setup the newest version 4.0.0-beta.17
2. Replace `player.ts` with this:
```
import { RpgPlayer, RpgPlayerHooks, Control, Components, RpgEvent } from '@rpgjs/server'
import VillagerEvent from './events/villager'

const player: RpgPlayerHooks = {
    onConnected(player: RpgPlayer) {
        player.name = 'YourName'
        player.setComponentsTop(Components.text('{name}'))
    },
    onInput(player: RpgPlayer, { input }) {
        if (input == Control.Back) {
            player.callMainMenu()
        }

        if (input == Control.Action) {
            const event = player.getCurrentMap()?.createDynamicEvent({
                x: 100,
                y: 100,
                event: VillagerEvent,
            })

            const clear = (event: RpgEvent) => {
                event.stopMoveTo();
                event.showAnimation('female', 'stand');

                setTimeout(() => {
                    event.getCurrentMap()?.removeEvent(event.id);
                }, 200)
            }

            Object.entries(event).forEach(([eventId, event]) => {
                event.moveTo(player, {
                    onComplete: () => clear(event),
                }).subscribe();
            });
        }
    },
    async onJoinMap(player: RpgPlayer) {
    }
}

export default player
```

3. Replace `villager.ts` with this:
```
import { RpgEvent, EventData, RpgPlayer, Speed } from '@rpgjs/server'

@EventData({
    name: 'EV-1',
    hitbox: {
        width: 32,
        height: 16
    }
})
export default class VillagerEvent extends RpgEvent {
    onInit() {
        this.speed = Speed.Fastest;
        this.setGraphic('female');
        this.through = true;
        this.throughOtherPlayer = true;
    }
}
```

4. Run application
5. Click space (action button) multiple times and try to change the map

Result: engine tries to complete `Subscription` after 200 milliseconds, but it is impossible because the event is not anymore loaded (this is my assuption)

**Browser (client) console:**
```
GameEngine.ts:125 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'complete')
    at GameEngineClient.resetObjects (GameEngine.ts:125:34)
    at Object.next (RpgClientEngine.ts:528:37)
    at ConsumerObserver2.next (Subscriber.ts:161:25)
    at Subscriber2._next (Subscriber.ts:119:22)
    at Subscriber2.next (Subscriber.ts:75:12)
    at Subject.ts:68:20
    at errorContext (errorContext.ts:29:5)
    at Subject2.next (Subject.ts:61:5)
    at BehaviorSubject2.next (BehaviorSubject.ts:37:15)
    at Socket2.<anonymous> (world.ts:96:23)
```

It is also related to: https://community.rpgjs.dev/d/135-what-is-efficient-way-of-guided-skills

For now, my events throw skills which are `RpgEvent`s too and I suppose that is ineffective but for now I do not have any other idea.

**Comment by RSamaium** [comment]
Thanks, I'm working on it
